# -*- coding: utf-8 -*-
"""Chapter 08 다이나믹 프로그래밍의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h_RtgMNExhHo9-3UpadCoHeuPgnb1nUD

8-1.py 피보나치 함수 소스코드
"""

def fibo(x):
  if x == 1 or x == 2:
    return 1
  return fibo(x-1) + fibo(x-2)

print(fibo(4))

"""8-2.py 피보나치 수열 소스코드(재귀적)"""

d = [0] * 100

def fibo(x):
  if x == 1 or x == 2:
    return 1
  if d[x] != 0:
    return d[x]
  d[x] = fibo(x-1) + fibo(x-2)
  return d[x]

print(fibo(99))

"""8-3.py 호출되는 함수 확인"""

d = [0] * 100

def fibo(x):
  print('f(' + str(x) + ')',end = ' ')
  if x == 1 or x == 2:
    return 1
  if d[x] != 0:
    return d[x]
  d[x] = fibo(x-1) + fibo(x-2)
  return d[x]

fibo(6)

"""8-4.py 피보나치 수열 소스코드(반복적)"""

d = [0] * 100

d[1] = 1
d[2] = 1
n = 99

for i in range(3,n+1):
  d[i] = d[i-1]+d[i-2]

print(d[n])

"""1로 만들기"""



"""개미전사"""



"""바닥 공사"""

